services:
  php:
    container_name: geo-sapiens-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./application:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - geo-sapiens-network

  nginx:
    container_name: geo-sapiens-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./application:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - geo-sapiens-network

  mysql:
    container_name: geo-sapiens-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - geo-sapiens-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - geo-sapiens-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  phpmyadmin:
    container_name: geo-sapiens-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8888:80"
    networks:
      - geo-sapiens-network
    environment:
      PMA_HOST: geo-sapiens-mysql
    depends_on:
      - mysql

networks:
  geo-sapiens-network:
    driver: bridge

volumes:
  geo-sapiens-data:
    driver: local
